### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by OrangeTabia** [OrangeTabia/Python-Project#17]
Add media queries for mobile

**Comment by llfbh33** [comment]
- 1180px and larger:
          - Need to adjust the layout of the information provided on expenses
                     dropdown cards when closed.
          - Need to change comment input box to fit properly
- 1180px - 1000px:
          - Need to adjust the expenses drop down cards so they stay size
                     adjusted, as well as the internal contents.
          - -------
          - Need to adjust the layout of the information provided on expenses
                     dropdown cards when closed.
          - Need to change comment input box to fit properly
- 1000px - 600px:
          - I think we should put the friends as a dropdown menu under the second
                     navigation, maybe a dropdown with our dev links next to it?  or set
                     as a button on the main nav bar to open a modal.
- 600px and smaller:
          - We need to adjust the main nav bar button spacing, or maybe put all those
                      links in the profile button drop down
          - Need to adjust the font size and button size for the second navigation

I did not account for the modals yet.  But a lot of the sizing was set up with stretch in mind already so I don't think this will be to much extra work.

**Comment by OrangeTabia** [comment]
- [ ] media queries on landing page
- [ ] layout of friends expenses names on dashboard for tiny screens
- [ ] drop down for expense card on friends page
- [ ] drop down for expense card on expenses page
- [ ] comments input size (put comments below edit and delete buttons)

**Comment by llfbh33** [comment]
Adjusted expenses card length
Adjusted overlap on dev container from expenses
