### ISSUE TITLE
How To Page

### ISSUE THREAD

**Issue by OrangeTabia** [OrangeTabia/Python-Project#27]
- since the website is not as "intuitive", create a walkthrough with step by step instructions and features on how to use and navigate website as both a payer and receiver
- maybe add upon sign up?

**Comment by llfbh33** [comment]
Could not get add on signup to work.  When signing up the user is set as the session user then automatically navigated to the dashboard, leaving the current function and not opening the walkthrough modals.  I tried to create a useEffect that would check the time the user was created compared to the current time which can sort of work,  But again it may not work in different time zones.  The best way to do it I can think of is add a boolean column to the users that is set to false on initial signup as default.  When on the landing page it will check this users column, if it is false, it will walkthrough the modal, then update the user to true before closing out.

**Comment by llfbh33** [comment]
Walkthrough on sign up works and ability to access it is in the dropdown profile button.
